### ISSUE TITLE
Move away from neovim

### ISSUE THREAD

**Issue by DJMcMayhem** [DJMcMayhem/V#10]
Neovim is poorly supported on windows (not sure about mac). It would be nice to have it run on vim 8 instead of neovim for portability. This will require moving some logic into a vimscript "main function" of sorts, but I think that's OK. Doing that would probably also fix the [timing bug](https://github.com/DJMcMayhem/V/issues/9)

**Comment by RikerW** [comment]
It's default on mac. At least on OS X yosemite, neovim came installed by default, but vi and vim didn't. (they both were aliased to neovim)

**Comment by vihanb** [comment]
Wait wat it is otherway around 99% sure @RikerW

**Comment by vihanb** [comment]
I have done research and concluded vim is installed my default on all OS X and vi is mapped to vim

**Comment by kritixilithos** [comment]
@vihanb `vi` wasn't aliased to vim for me

**Comment by vihanb** [comment]
@kritixilithos I suppose it depends on the original version of mac your computer had installed but I can guarantee two things:

 - Neovim is not installed on macs by default
 - Vim is

**Comment by RikerW** [comment]
Okay, @vihanb  is right. I clean installed OS X 10.11 and Vim was installed by default and `vi` was aliased to `vim`.

**Comment by DJMcMayhem** [comment]
Closed in https://github.com/DJMcMayhem/V/commit/aced470fad746a90415ff2144efea660f0af75b8
