### ISSUE TITLE
Migrate python-commands to vimscript commands

### ISSUE THREAD

**Issue by DJMcMayhem** [DJMcMayhem/V#3]
Currently, commands are implemented in python. This is a big problem since python doesn't have full access to the state of vim when the command starts. The simple obvious solution is to replace all of the python commands with vimscript commands. That will allow the python code to be simplified, since we won't need to track things like mode, and count.

**Comment by DJMcMayhem** [comment]
This is currently in progress on a different repository: [Vigor](https://github.com/DJMcMayhem/vigor). Once Vigor supports all of the commands that V does, I will merge the two back together.

**Comment by vihanb** [comment]
why use separate repo and not branch

**Comment by DJMcMayhem** [comment]
¯\_(ツ)_/¯

**Comment by DJMcMayhem** [comment]
Everything is done! All logic, operators, motions, new commands, mappings, etc. are now implemented purely from within neovim! And beyond that, a ton of bugfixes, new operators and new features were added. I'm really happy about this particular milestone. Up next on the chopping block is better UTF-8 support, then after that maybe some more math.

**Comment by vihanb** [comment]
@DJMcMayhem +100 10/10 for less python :P

**Comment by DJMcMayhem** [comment]
It's not about removing python, it's about having it in a state where adding new features is actually remotely possible. I'm going to add more python down the road.
